env:
  CHRONICLE_NAME: chronicle
  CHRONICLE_VERSION: 1.0.0
  CHRONICLE_TRIPLET: ${CHRONICLE_NAME}-${CHRONICLE_VERSION}-${CIRRUS_OS}

linux_build_task:
  container:
    image: gcc:latest

  apt_script:
    - chmod +x .ci/linux/*.sh # I know, I dev on Windows -_-
    - .ci/linux/apt-deps.sh

  boost_cache:
    folder: boost_1_68_0
    populate_script:
      - .ci/linux/boost-download.sh
  
  boost_build_script:
    - .ci/linux/boost-install.sh
  
  lame_cache:
    folder: lame-3.100
    populate_script:
      - .ci/linux/lame-download.sh
  
  lame_build_script:
    - .ci/linux/lame-install.sh

  rtaudio_cache: 
    folder: rtaudio-5.0.0
    populate_script:
      - .ci/linux/rtaudio-download.sh

  rtaudio_build_script:
    - .ci/linux/rtaudio-install.sh

  build_script:
    - .ci/linux/chronicle-build.sh

  dist_script:
    - .ci/linux/dist.sh

windows_build_task:
  # Most sources need to be built from scratch, since the mingw version of pkg-config ignores PKG_CONFIG_PATH
  env:
    # Let's do it just for conveniences' sake
    PKG_CONFIG_PATH: /usr/local/lib/pkgconfig
  container:
    image: ubuntu:latest

  apt_script:
    - .ci/mingw-64/apt-script.sh

  lame_cache:
    folder: lame-3.100
    populate_script:
      - .ci/mingw-64/lame-download-script.sh
  
  lame_build_script:
    - .ci/mingw-64/lame-install-script.sh

  libogg_cache:
    folder: libogg-1.3.3
    populate_script:
      - .ci/mingw-64/libogg-download.sh

  libogg_install_script:
    - .ci/mingw-64/libogg-install.sh

  libvorbis_cache:
    folder: libvorbis-1.3.6
    populate_script:
      - .ci/mingw-64/libvorbis-download.sh

  libvorbis_install_script:
    - .ci/mingw-64/libvorbis-install.sh

  libflac_cache:
    folder: flac-1.3.2
    populate_script:
      - .ci/mingw-64/libflac-download.sh

  libflac_install_script:
    - .ci/mingw-64/libflac-install.sh

  libspeex_cache:
    folder: speex-1.2.0
    populate_script:
      - .ci/mingw-64/libspeex-download.sh

  libspeex_install_script:
    - .ci/mingw-64/libspeex-install.sh
  
  libsndfile_cache:
    folder: libsndfile-1.0.28
    populate_script:
      - .ci/mingw-64/libsndfile-download-script.sh # <---- Get libflac, libogg, libvorbis, vorbisenc

  libsndfile_build_script:
    - .ci/mingw-64/libsndfile-install-script.sh

  rtaudio_cache: 
    folder: rtaudio
    populate_script:
      - .ci/mingw-64/rtaudio-download-script.sh

  rtaudio_build_script:
  # Depends on libsndfile
    - .ci/mingw-64/rtaudio-install-script.sh

  ncurses_cache:
    folder: ncurses-6.1
    populate_script:
      - .ci/mingw-64/ncurses-download-script.sh
  
  ncurses_build_script:
    - .ci/mingw-64/ncurses-install-script.sh

  boost_cache:
    folder: boost_1_68_0
    populate_script:
      - .ci/mingw-64/boost-download-script.sh

  boost_build_script:
    - .ci/mingw-64/boost-install-script.sh

  build_script:
    - chmod +x .ci/mingw-64/chronicle-build.sh
    - .ci/mingw-64/chronicle-build.sh

  dist_script:
    - .ci/mingw-64/dist.sh
    