linux_build_task:
  container:
    image: gcc:latest

  submodules_script:
    - git submodule init
    - git submodule update
  
  apt_script:
    - apt-get update -qq
    - apt-get install libncurses5-dev libsndfile1-dev libasound2 libasound2-dev git build-essential libtool libtool-bin wget -qq -y

  boost_cache:
    folder: boost_1_68_0
    populate_script:
      - wget https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz
      - tar xf boost_1_68_0.tar.gz
      - cd boost_1_68_0
      - ./bootstrap.sh --with-libraries=system,filesystem
  
  boost_build_script:
    - cd boost_1_68_0
    - ./b2 install
  
  lame_cache:
    folder: lame-3.100
    populate_script:
      - wget https://netix.dl.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz
      - tar xf lame-*
      - cd lame-3.100
      - ./configure --disable-decoder
  
  lame_build_script:
    - cd lame-3.100
    - make
    - make install

  rtaudio_cache: 
    folder: rtaudio-5.0.0
    populate_script:
      - wget http://www.music.mcgill.ca/~gary/rtaudio/release/rtaudio-5.0.0.tar.gz
      - tar xf rtaudio-*
      - cd rtaudio-5.0.0
      - ./configure

  rtaudio_build_script:
    - cd rtaudio-5.0.0
    - make
    - make install

  build_script:
    - chmod +x autogen.sh
    - ./autogen.sh
    - mkdir -p chronicle-v1.0.0-linux
    - cd chronicle-v1.0.0-linux
    - ../configure && make

  dist_script:
    - cd chronicle-v1.0.0-linux
    - make mostlyclean
    - ls -al
    - deps=$(ldd ./chronicle.exe | awk '/~*mingw*/ {print $3}')
    - for dep in $deps; do cp $dep . ;done
    - cp ../LICENCE .
    - cp ../README.md .
    - cp ../CHANGELOG.md .
    - cd ..
    - tar zcf chronicle-v1.0.0-linux.tar.gz chronicle-v1.0.0-linux

windows_build_task:
  # Most sources need to be built from scratch, since the mingw version of pkg-config ignores PKG_CONFIG_PATH
  env:
    # Let's do it just for conveniences' sake
    PKG_CONFIG_PATH: /usr/local/lib/pkgconfig
  container:
    image: ubuntu:latest

  apt_script:
    - .ci/mingw-64/apt-script.sh

  submodules_script:
    - .ci/mingw-64/git-submodules-script.sh

  lame_cache:
    folder: lame-3.100
    populate_script:
      - .ci/mingw-64/lame-download-script.sh
  
  lame_build_script:
    - .ci/mingw-64/lame-install-script.sh

  libsndfile_cache:
    folder: libsndfile-1.0.28
    populate_script:
      - .ci/mingw-64/libsndfile-download-script.sh # <---- Get libflac, libogg, libvorbis, vorbisenc

  libsndfile_build_script:
    - .ci/mingw-64/libsndfile-install-script.sh

  rtaudio_cache: 
    folder: rtaudio
    populate_script:
      - .ci/mingw-64/rtaudio-download-script.sh

  rtaudio_build_script:
  # Depends on libsndfile
    - .ci/mingw-64/rtaudio-install-script.sh

  ncurses_cache:
    folder: ncurses-6.1
    populate_script:
      - .ci/mingw-64/ncurses-download-script.sh
  
  ncurses_build_script:
    - .ci/mingw-64/ncurses-install-script.sh

  boost_cache:
    folder: boost_1_68_0
    populate_script:
      - .ci/mingw-64/boost-download-script.sh

  boost_build_script:
    - .ci/mingw-64/boost-install-script.sh

  build_script:
    - .ci/mingw-64/chronicle-build.sh