container:
  image: gcc:latest

install_deps_task:
  script:
    - apt-get update -qq
    - apt-get install libncurses5-dev libsndfile1-dev libboost-filesystem-dev libboost-system-dev libasound2 libasound2-dev -qq -y

build_task:
  depends_on:
    - install_deps
  lame_cache:
    folder: lame
    populate_script:
      - mkdir -p lame
      - cd lame
      - wget https://netix.dl.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz
      - tar xf lame-*
      - cd lame-3.100
      - ./configure --disable-decoder
      - make
      - make install

  rtaudio_cache: 
    folder: rtaudio
    populate_script:
      - mkdir -p rtaudio
      - cd rtaudio
      - wget http://www.music.mcgill.ca/~gary/rtaudio/release/rtaudio-5.0.0.tar.gz
      - tar xf rtaudio-*
      - cd rtaudio-5.0.0
      - ./configure
      - make
      - make install
  script:
  - ./autogen.sh
  - ./configure && make